#!/bin/bash

cd /tmp
odl --accept-license --arch na --component sqlcl --version 4.2 --os na
unzip sqlcl-4.2.0.17.096.0933-no-jre.zip
echo "Pre-upgrade version:"
sql -v
sudo rm -rf /opt/sqlcl
sudo mv sqlcl /opt/sqlcl/
echo "Post-upgrade version:"
sql -v
